export const MOCK_GUIAS= [
{id_guia:1,nombre:"Alex",apellido:"Gimenez",foto:"https://ciudaddemendoza.gob.ar/wp-content/uploads/2023/04/Copa-XCO.jpg",descripcion:`Breve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guia`},
{
id_guia:2,nombre:"Alejandra",apellido:"Villalba",foto:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSffALbOkfaL6UoDgu4C2sPVa0j8HVWXUZDwj2bkksHhiYCTX2w",descripcion:`Breve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guia`},
{
id_guia:3,nombre:"Martin",apellido:"Coria",foto:"https://www.superprof.es/imagenes/anuncios/profesor-home-profesor-educacion-fisica-ofrece-sus-clases-line-para-mejorar-calidad-vida-alcanzar-tus-objetivos.jpg",descripcion:`Breve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guia`},
{
id_guia:4,nombre:"Fernando",apellido:"Iglesias",foto:"https://www.superprof.es/imagenes/anuncios/profesor-home-tecnico-superior-actividades-montana-ofrece-clases-escalada-teoricas-practicas.jpg",descripcion:`Breve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guia`},
{
id_guia:5,nombre:"Juan",apellido:"Swcharkopf",foto:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRPKK1kTDaRrZDMcV-NcESW92od4WeL43E2O-kHhcwaWZBCzVN0",descripcion:`Breve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guia`},
{
id_guia:6,nombre:"Luisana",apellido:"Rios",foto:"https://cloudfront-us-east-1.images.arcpublishing.com/infobae/BZ4FVTHGXJCURJIF3V43SM3U7Y.jpg",descripcion:`Breve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guiaBreve descripcion del guia`
}
]