# Generated by Django 4.2.1 on 2023-06-17 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fecha_apertura',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_factura',
            new_name='factura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_recorrido',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='aNombreCliente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='clienteUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='vendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vendedorUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='./Frontend-Angular/MountainHike/src/assets/img/blog'),
        ),
        migrations.AlterField(
            model_name='guias',
            name='foto',
            field=models.ImageField(blank=True, upload_to='./Frontend-Angular/MountainHike/src/assets/img/nosotros'),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='dificultad',
            field=models.ImageField(upload_to='./Frontend-Angular/MountainHike/src/assets/img/recorridos'),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='./Frontend-Angular/MountainHike/src/assets/img/recorridos'),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='FechaRecorrido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mountain_Hike_app.guias')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_Hike_app.recorridos')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaRecorrido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Mountain_Hike_app.fecharecorrido'),
            preserve_default=False,
        ),
    ]
