# Generated by Django 4.2.1 on 2023-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('articulo', models.CharField(max_length=2000)),
                ('imagen', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
