# Generated by Django 4.2.1 on 2023-06-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0002_rename_fecha_apertura_factura_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fecharecorrido',
            options={'verbose_name': 'Fecha de Recorrido', 'verbose_name_plural': 'Fechas de Recorrido'},
        ),
        migrations.AlterModelTable(
            name='fecharecorrido',
            table='FechaRecorrido',
        ),
    ]
