# Generated by Django 4.2.1 on 2023-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0003_recorridos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
