# Generated by Django 4.2.1 on 2023-06-20 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0004_recorridos_cantidadmaximadeparticipantes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nro_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidadParticipantes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mountain_Hike_app.factura'),
        ),
    ]
