# Generated by Django 4.2.1 on 2023-05-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0004_alter_recorridos_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentrada',
            options={'verbose_name': 'Entrada del blog', 'verbose_name_plural': 'Entradas del blog'},
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('nro_reserva', models.IntegerField()),
                ('valor', models.FloatField()),
                ('id_recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_Hike_app.recorridos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_Hike_app.usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
