# Generated by Django 4.2.1 on 2023-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0004_alter_recorridos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('foto', models.URLField()),
                ('descripcion', models.TextField(max_length=2500)),
            ],
            options={
                'verbose_name': 'guia',
                'verbose_name_plural': 'guias',
                'db_table': 'guia',
            },
        ),
        migrations.AlterModelOptions(
            name='blogentrada',
            options={'verbose_name': 'Entrada del blog', 'verbose_name_plural': 'Entradas del blog'},
        ),
    ]
