# Generated by Django 4.2 on 2023-05-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0005_alter_blogentrada_options_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('articulo', models.TextField()),
                ('imagen', models.URLField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('foto', models.URLField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
                'db_table': 'guia',
            },
        ),
        migrations.DeleteModel(
            name='BlogEntrada',
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
