# Generated by Django 4.2.1 on 2023-05-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0005_guias_alter_blogentrada_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('articulo', models.TextField()),
                ('imagen', models.URLField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('tipo', models.CharField(max_length=1)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_Hike_app.usuario')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('nro_reserva', models.IntegerField()),
                ('valor', models.FloatField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_Hike_app.factura')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.DeleteModel(
            name='BlogEntrada',
        ),
        migrations.AlterModelOptions(
            name='guias',
            options={'verbose_name': 'Guia', 'verbose_name_plural': 'Guias'},
        ),
        migrations.AlterField(
            model_name='guias',
            name='apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='guias',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guias',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_Hike_app.recorridos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mountain_Hike_app.usuario'),
        ),
    ]
