# Generated by Django 4.2.1 on 2023-05-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0006_admin_blog_factura_reserva_delete_blogentrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
