# Generated by Django 4.2.1 on 2023-06-03 17:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0008_customuser_delete_admin_alter_factura_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='estado_reserva',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=30)),
                ('estado_reserva', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Mountain_Hike_app.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
