# Generated by Django 4.2.1 on 2023-06-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mountain_Hike_app', '0009_remove_customuser_ciudad_remove_customuser_edad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customUser',
        ),
    ]
